-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")
--
-- NOTE: the "open explorer on startup" autocmd lives in options.lua, not here.
-- This file is loaded on the VeryLazy event (after VimEnter when nvim is opened
-- with no file args), which is too late to register a VimEnter autocmd.
